### ISSUE TITLE
Local bin path configuration issue

### ISSUE THREAD

**Issue by Abhinavcode13** [Upsonic/Upsonic#104]
Bug raised by one of the users: cc @MahdyMusave
```
WARNING: The script dotenv is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script mprof is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script openai is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script langsmith is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script upsonic is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script langchain-server is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script computerassistant is installed in '/home/seyadkali/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mitmproxy 10.2.3 requires mitmproxy-rs<0.6,>=0.5.1, which is not installed.
mitmproxy 10.2.3 requires urwid-mitmproxy<2.2,>=2.1.1, which is not installed.
censys 2.2.12 requires requests>=2.29.0, but you have requests 2.28.2 which is incompatible.
crackmapexec 5.4.0 requires aioconsole<0.4.0,>=0.3.3, but you have aioconsole 0.7.0 which is incompatible.
crackmapexec 5.4.0 requires masky<0.2.0,>=0.1.1, but you have masky 0.2.0 which is incompatible.
crackmapexec 5.4.0 requires minikerberos==0.3.3, but you have minikerberos 0.4.4 which is incompatible.
crackmapexec 5.4.0 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 5.2.dev0 which is incompatible.
crackmapexec 5.4.0 requires paramiko<3.0.0,>=2.7.2, but you have paramiko 3.4.0 which is incompatible.
crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.8.1 which is incompatible.
crackmapexec 5.4.0 requires termcolor<2.0.0,>=1.1.0, but you have termcolor 2.4.0 which is incompatible.
crackmapexec 5.4.0 requires xmltodict<0.13.0,>=0.12.0, but you have xmltodict 0.13.0 which is incompatible.
aioquic 1.0.0 requires cryptography>=42.0.0, but you have cryptography 41.0.3 which is incompatible.
theharvester 4.6.0 requires aiodns==3.1.1, but you have aiodns 3.2.0 which is incompatible.
theharvester 4.6.0 requires aiohttp==3.9.3, but you have aiohttp 3.9.1 which is incompatible.
theharvester 4.6.0 requires aiosqlite==0.20.0, but you have aiosqlite 0.17.0 which is incompatible.
theharvester 4.6.0 requires censys==2.2.11, but you have censys 2.2.12 which is incompatible.
theharvester 4.6.0 requires certifi==2024.2.2, but you have certifi 2023.11.17 which is incompatible.
theharvester 4.6.0 requires netaddr==1.2.1, but you have netaddr 0.10.1 which is incompatible.
theharvester 4.6.0 requires playwright==1.42.0, but you have playwright 0.0.0 which is incompatible.
theharvester 4.6.0 requires python-dateutil==2.9.0.post0, but you have python-dateutil 2.9.0 which is incompatible.
theharvester 4.6.0 requires requests==2.31.0, but you have requests 2.28.2 which is incompatible.
theharvester 4.6.0 requires retrying==1.3.4, but you have retrying 1.3.3 which is incompatible.
theharvester 4.6.0 requires setuptools==69.2.0, but you have setuptools 68.1.2 which is incompatible.
theharvester 4.6.0 requires shodan==1.31.0, but you have shodan 1.30.1 which is incompatible.
theharvester 4.6.0 requires slowapi==0.1.9, but you have slowapi 0.1.4 which is incompatible.
theharvester 4.6.0 requires uvicorn==0.28.0, but you have uvicorn 0.29.0 which is incompatible.
fastapi 0.110.0 requires starlette<0.37.0,>=0.36.3, but you have starlette 0.37.2 which is incompatible.
mitmproxy 10.2.3 requires aioquic<0.10,>=0.9.24, but you have aioquic 1.0.0 which is incompatible.
mitmproxy 10.2.3 requires asgiref<3.8,>=3.2.10, but you have asgiref 3.8.1 which is incompatible.
mitmproxy 10.2.3 requires pyOpenSSL<24.1,>=22.1, but you have pyopenssl 24.1.0 which is incompatible.
```

**Comment by Mideky-hub** [comment]
First, you need to add : "/home/seyadkali/.local/bin" to your PATH environement variable.

Then, try to install the requirements through pipx to avoid incompatibility : 
"pipx install -r requirements.txt" at the root directory of the project.

If this still doesn't work with another incompatibility : 
"pipx install -f -r "requirements.txt"

Let me know if there's other bug appearing while/after the recommandations.

**Comment by Macaulay1234** [comment]
> Bug raised by one of the users: cc @MahdyMusave
> ```
> WARNING: The script dotenv is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> WARNING: The script mprof is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> WARNING: The script openai is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> WARNING: The script langsmith is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> WARNING: The script upsonic is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> WARNING: The script langchain-server is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> WARNING: The script computerassistant is installed in '/home/seyadkali/.local/bin' which is not on PATH.
> Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> mitmproxy 10.2.3 requires mitmproxy-rs<0.6,>=0.5.1, which is not installed.
> mitmproxy 10.2.3 requires urwid-mitmproxy<2.2,>=2.1.1, which is not installed.
> censys 2.2.12 requires requests>=2.29.0, but you have requests 2.28.2 which is incompatible.
> crackmapexec 5.4.0 requires aioconsole<0.4.0,>=0.3.3, but you have aioconsole 0.7.0 which is incompatible.
> crackmapexec 5.4.0 requires masky<0.2.0,>=0.1.1, but you have masky 0.2.0 which is incompatible.
> crackmapexec 5.4.0 requires minikerberos==0.3.3, but you have minikerberos 0.4.4 which is incompatible.
> crackmapexec 5.4.0 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 5.2.dev0 which is incompatible.
> crackmapexec 5.4.0 requires paramiko<3.0.0,>=2.7.2, but you have paramiko 3.4.0 which is incompatible.
> crackmapexec 5.4.0 requires pypsrp<0.8.0,>=0.7.0, but you have pypsrp 0.8.1 which is incompatible.
> crackmapexec 5.4.0 requires termcolor<2.0.0,>=1.1.0, but you have termcolor 2.4.0 which is incompatible.
> crackmapexec 5.4.0 requires xmltodict<0.13.0,>=0.12.0, but you have xmltodict 0.13.0 which is incompatible.
> aioquic 1.0.0 requires cryptography>=42.0.0, but you have cryptography 41.0.3 which is incompatible.
> theharvester 4.6.0 requires aiodns==3.1.1, but you have aiodns 3.2.0 which is incompatible.
> theharvester 4.6.0 requires aiohttp==3.9.3, but you have aiohttp 3.9.1 which is incompatible.
> theharvester 4.6.0 requires aiosqlite==0.20.0, but you have aiosqlite 0.17.0 which is incompatible.
> theharvester 4.6.0 requires censys==2.2.11, but you have censys 2.2.12 which is incompatible.
> theharvester 4.6.0 requires certifi==2024.2.2, but you have certifi 2023.11.17 which is incompatible.
> theharvester 4.6.0 requires netaddr==1.2.1, but you have netaddr 0.10.1 which is incompatible.
> theharvester 4.6.0 requires playwright==1.42.0, but you have playwright 0.0.0 which is incompatible.
> theharvester 4.6.0 requires python-dateutil==2.9.0.post0, but you have python-dateutil 2.9.0 which is incompatible.
> theharvester 4.6.0 requires requests==2.31.0, but you have requests 2.28.2 which is incompatible.
> theharvester 4.6.0 requires retrying==1.3.4, but you have retrying 1.3.3 which is incompatible.
> theharvester 4.6.0 requires setuptools==69.2.0, but you have setuptools 68.1.2 which is incompatible.
> theharvester 4.6.0 requires shodan==1.31.0, but you have shodan 1.30.1 which is incompatible.
> theharvester 4.6.0 requires slowapi==0.1.9, but you have slowapi 0.1.4 which is incompatible.
> theharvester 4.6.0 requires uvicorn==0.28.0, but you have uvicorn 0.29.0 which is incompatible.
> fastapi 0.110.0 requires starlette<0.37.0,>=0.36.3, but you have starlette 0.37.2 which is incompatible.
> mitmproxy 10.2.3 requires aioquic<0.10,>=0.9.24, but you have aioquic 1.0.0 which is incompatible.
> mitmproxy 10.2.3 requires asgiref<3.8,>=3.2.10, but you have asgiref 3.8.1 which is incompatible.
> mitmproxy 10.2.3 requires pyOpenSSL<24.1,>=22.1, but you have pyopenssl 24.1.0 which is incompatible.
> ```

**Comment by Macaulay1234** [comment]
> First, you need to add : "/home/seyadkali/.local/bin" to your PATH environement variable.
> 
> Then, try to install the requirements through pipx to avoid incompatibility : 
> "pipx install -r requirements.txt" at the root directory of the project.
> 
> If this still doesn't work with another incompatibility : 
> "pipx install -f -r "requirements.txt"
> 
> Let me know if there's other bug appearing while/after the recommandations.

**Comment by Bartupso** [comment]
Sorry for the late reply. We will have a new version soon
