### ISSUE TITLE
Assistant unusable LLM Issues - Windows 10

### ISSUE THREAD

**Issue by JIMBYLAD** [Upsonic/Upsonic#109]
Hello, I made a GitHub account just to post this , so I hope I can get some help.

I am running into some very frustrating issues on Windows (64 bit) when trying to use this assistant, I can't get it to give me any output, all I can do is launch the app via CMD.

I am very interested in testing this application, The application has access to my API key and I'm a premium open ai user. I am also from Australia I'm not sure if this affects what models are useable through my API key
(right now none of the models work).  

Things I've tried:
reset API Key
tried all available models in the application 
disable VPN
tried to update URL in settings

This is what happens when I try to use any version of gpt 4 including 4o:

HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 404 Not Found"
Error in process_text Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Updating from thread EXCEPTION: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
State updated: idle

This is what happens when I try to use gpt 3.5:

C:\Users\jack\AppData\Local\Programs\Python\Python312\Lib\site-packages\gpt_computer_assistant\utils\artifacts\history_default.db
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
Retrying request to /chat/completions in 0.932674 seconds
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
Retrying request to /chat/completions in 1.678915 seconds
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
Retrying request to /chat/completions in 3.818514 seconds

This is what happens when I try to use the other models including groq:

EXCEPTION: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/chat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000253CC3C4F20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

This what happens when I try to change url in settings (not sure if you have to do this, just playing around for solution): 

NameError: name 'save_openai_url' is not defined. Did you mean: 'load_openai_url'?

Any assistance is much appreciated, I understand this is a work in progress and is temperamental. 
Amazing work so far!

**Comment by Mideky-hub** [comment]
For gpt-4o, did you request your API key correctly? If so, did you add it correctly to your environment path? If so, did you set up your API settings for automatic credits? If so, can you refeer to ' https://help.openai.com/en/articles/6843909-rate-limits-and-429-too-many-requests-errors' to see if you don't have any other issues or a missed step in the setup.

**Comment by onuratakan** [comment]
Hi actualy there is an problem by your location. For now you can choose gpt-4-turbo or 3.5-turbo as well with latest update.


```console
pip3 install gpt-computer-assistant[default]
```
