### ISSUE TITLE
Error on each click

### ISSUE THREAD

**Issue by parsabe** [Upsonic/Upsonic#11]
On each click on different parts error occurs. Why is that?

**Comment by onuratakan** [comment]
Ouu, can i see?

**Comment by anekant7** [comment]
3. Add - confirm for approval flow - FE 


Shubham 
6. Create certificate - Status - BE & FE - backend pendnig


Tanmay
7. Cerate certificate - change history - FE - Populate fields - Can close after populating date time picker 
8. Create certificate - handover & handbook section - FE - Can close after validation senario 



Tanuja 
9. CS - Section 4 - FE (Save functionality only text fields) - ##


Tanmay
10. CS - Section 3 - FE (Save, Grid, Add isolation) 



Tanuja
11. CS - Section 2 - FE 

	1. Adding & removal file - FE - Upload file & save it session 

	2. Add site plan - FE 

Tanmay
12. CS - Section 1 New  - FE - Save functionality - [Sub Item as below]

	4. Create certificate - field - authorized person - auto dropdown populate - FE - 

	5. Create certificate - field - site field - Auto drop down pupulate - FE - 



**Sukhada - Need to rectify completed or not ?

13. CS - Admin - Download Certificate - FE - CSV is done - Partially Completed -  pdf only pending {UX Not available - Durgesh} 

14. CS - Contractor - Download Certificate - FE

**Comment by fatsopanda** [comment]
can others contribute to this project @onuratakan

**Comment by onuratakan** [comment]
> can others contribute to this project @onuratakan

yeah sure, it will be so amazing
