### ISSUE TITLE
MacOS Sonoma 14.5 Screen Recording Permissions?

### ISSUE THREAD

**Issue by felixlu07** [Upsonic/Upsonic#125]
Hey @onuratakan. I'm trying to run it but it seems like no matter what I do, GPT assistant is unable to see the contents of my screen. I got a feeling that this has to do with the fact that I need to give permissions to the application to do screenshots/screen recordings, however, I'm not sure what is the "application" nam that I should be giving permissions to on my Mac.

I already have the following, but what should I be adding so that GPT Computer Assistant is able to "see"?
<img width="486" alt="image" src="https://github.com/onuratakan/gpt-computer-assistant/assets/44922675/96d60d6a-1243-4263-82ae-a1eb3328e8a5">

**Comment by onuratakan** [comment]
Oh, thank you for this information. Actualy there is some bugs like this. Can you provide more information?.

Macbook  type
python version

**Comment by felixlu07** [comment]
I'm running Macbook Pro 14-inch 2023, Running Apple M2 Pro chip, OS-Sonoma 14.5 (23F79)
As for Python, I'm using Python 3.11 at the moment.

**Comment by Bartupso** [comment]
I suggest Python 3.10 version. We publish new version soon
