### ISSUE TITLE
Accessing the wrong LLM API Key under windows 11

### ISSUE THREAD

**Issue by Adamchanadam** [Upsonic/Upsonic#134]
When I change the LLM Setting for different model , it always return error.
It happened when I use os.environ to save my 'OPENAI_API_KEY', it consistently retrieves the incorrect value, such as 'GOOGLE_API_KEY' , or groq...etc

Here's one of my error code received after execute the latest version 0.13.0 , event I saved my OpenAI API Key via the GPT computer assistant interface. 

  File "C:\Users\adam\anaconda3\envs\gpt_comp_env\Lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: AIzaSy***************************s8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Updating from thread EXCEPTION: Error code: 401 - {'error': {'message': 'Incorrect API key provided: AIzaSy***************************s8. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
State updated: idle

**Comment by onuratakan** [comment]
Hi can you use the llm settings

and don't forget to update

```console
pip3 install gpt-computer-assistant[default]
```


![image](https://github.com/onuratakan/gpt-computer-assistant/assets/41792982/7aecae45-8612-450f-8621-9c1fba8d94d6)
