### ISSUE TITLE
error on install app 

### ISSUE THREAD

**Issue by Paaayman** [Upsonic/Upsonic#140]
![Screenshot 2024-06-14 155657](https://github.com/onuratakan/gpt-computer-assistant/assets/125666427/081942dd-7dfb-4610-af4c-868238f30e98)

**Comment by onuratakan** [comment]
Oh hi, yes we have some problems for now. But you can use developer installation as well.

**Comment by onuratakan** [comment]
Hi for now we just removed native app support.
