### ISSUE TITLE
Download getting stuck and Bitdefender Infected file detected.

### ISSUE THREAD

**Issue by DareDevil2000** [Upsonic/Upsonic#141]
![screenshot_298](https://github.com/onuratakan/gpt-computer-assistant/assets/64276640/a163c682-a3c7-4083-925e-d0b191a560a9)
The file is being deleted upon download, and the exe file is getting stuck at 84% after pause and resume. It asks for authentication again and again, even though I gave my GitHub email and pass for authentication.

**Comment by onuratakan** [comment]
Hi, its a general problem after bundling python files. These alerts are false positive. But we just removed native app installations. For now just pip3.
