### ISSUE TITLE
computerassistant not working

### ISSUE THREAD

**Issue by GarvGarg3** [Upsonic/Upsonic#180]
The command isnt working on my git bash

**Comment by onuratakan** [comment]
Is there any `command not found error`?

**Comment by GarvGarg3** [comment]
'computerassistant' is not a git command

**Comment by onuratakan** [comment]
> 'computerassistant' is not a git command

Actualy if you installed via pip3

you can use in a py file


```python
from gpt_computer_assistant import start

start()
```

**Comment by Macaulay1234** [comment]
> > 'computerassistant' is not a git command
> 
> Actualy if you installed via pip3
> 
> you can use in a py file
> 
> 
> ```python
> from gpt_computer_assistant import start
> 
> start()
> ```
