### ISSUE TITLE
How do I install this assistant?

### ISSUE THREAD

**Issue by Paaayman** [Upsonic/Upsonic#189]
For someone like me who doesn't know anything about programming and just wants to use a voice assistant on my system, executing these codes is very difficult. Please publish a video tutorial on YouTube about installing it in developer mode until the final file is ready. This will surely provide good feedback for the development of your program."

**Comment by bathiatuss** [comment]
Actually it easier to install it with command lines than the watching a video about it. You can check out the short writing about installation. [Click here](https://github.com/onuratakan/gpt-computer-assistant/wiki/Installation) to read the documents about installation.

**Comment by taozhiyuai** [comment]
actually I find different installation command in English version MD, Chinese version MD, and setting windows of app. it is confusing.
