### ISSUE TITLE
(PYL-R0401) Cyclic import found

### ISSUE THREAD

**Issue by onuratakan** [Upsonic/Upsonic#202]
## Description
Cyclic imports shall be avoided. Read why are they fatal [here](https://datagrok.org/python/circularimports/).

## Occurrences
There are 21 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/onuratakan/gpt-computer-assistant/issue/PYL-R0401/occurrences/](https://app.deepsource.com/gh/onuratakan/gpt-computer-assistant/issue/PYL-R0401/occurrences/)

**Comment by Abhinavcode13** [comment]
The provided link seems to be broken?
