### ISSUE TITLE
No module named 'utils.db'

### ISSUE THREAD

**Issue by ddlgap** [Upsonic/Upsonic#213]
from utils.db import load_api_key ModuleNotFoundError: 
No module named 'utils.db'

plzzzz   help

**Comment by onuratakan** [comment]
Hi, did you install on github or pypi? Which one?

**Comment by Dragon730** [comment]
> from utils.db import load_api_key ModuleNotFoundError: No module named 'utils.db'
> 
> plzzzz help

same

**Comment by Landerssss** [comment]
How to fix it?
