### ISSUE TITLE
Add Tongyi Qianwen AI

### ISSUE THREAD

**Issue by AlecoPlan** [Upsonic/Upsonic#215]
Please add Tongyi ai to this！！！！！

**Comment by onuratakan** [comment]
Hi actualy the qwen models already added. I cannot find Tongyi Qianwen AI.

**Comment by AlecoPlan** [comment]
It's Alibaba AI model

**Comment by AlecoPlan** [comment]
Great, thanks.

**Comment by Luoxin** [comment]
Actually I only found `ollama/qwen2.5`, but I would like to add the models `Qwen/QwQ-32B` and `Qwen/Qwen3-32B`.
