### ISSUE TITLE
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

### ISSUE THREAD

**Issue by Lyy0617** [Upsonic/Upsonic#217]
![image](https://github.com/user-attachments/assets/aae1c724-f4d6-435c-9d20-33ae14522ed3)
![PixPin_2024-08-05_15-19-28](https://github.com/user-attachments/assets/ea594925-e4bd-4795-a847-9e08066fb1d2)

**Comment by Bartupso** [comment]
Sorry for the late reply. We will have a new version soon
