### ISSUE TITLE
fail to pip install 'gpt-computer-assistant[wakeword]'

### ISSUE THREAD

**Issue by taozhiyuai** [Upsonic/Upsonic#223]
`taozhiyu@Mac ~ % pip install 'gpt-computer-assistant[wakeword]'

Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/, https://pypi.tuna.tsinghua.edu.cn/simple, https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: gpt-computer-assistant[wakeword] in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.22.3)
Collecting pvporcupine (from gpt-computer-assistant[wakeword])
  Downloading https://mirrors.aliyun.com/pypi/packages/03/c3/e80f3e0cc081287daa439d2d2200d500a44f7a2bfd0efe1c55ecafa2121d/pvporcupine-3.0.3-py3-none-any.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 248.6 kB/s eta 0:00:00
Collecting pyaudio (from gpt-computer-assistant[wakeword])
  Downloading https://mirrors.aliyun.com/pypi/packages/26/1d/8878c7752febb0f6716a7e1a52cb92ac98871c5aa522cba181878091607c/PyAudio-0.2.14.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-312
      creating build/lib.macosx-10.9-universal2-cpython-312/pyaudio
      copying src/pyaudio/__init__.py -> build/lib.macosx-10.9-universal2-cpython-312/pyaudio
      running build_ext
      building 'pyaudio._portaudio' extension
      creating build/temp.macosx-10.9-universal2-cpython-312
      creating build/temp.macosx-10.9-universal2-cpython-312/src
      creating build/temp.macosx-10.9-universal2-cpython-312/src/pyaudio
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c src/pyaudio/device_api.c -o build/temp.macosx-10.9-universal2-cpython-312/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyaudio
Failed to build pyaudio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyaudio)
`

**Comment by Bartupso** [comment]
Run it in a Python 3.10 environment in GPT Computer Assistant. We will share a new update soon.
