### ISSUE TITLE
Gemini pro after selecting, and after pasting api key, still getting an error :(

### ISSUE THREAD

**Issue by ChanduDhoni** [Upsonic/Upsonic#224]
System: EXCEPTION: Error code: 401 - {'error': {'message': 'Incorrect API key provided: CHANGE_ME. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

irrelevant error for gemini pro api

![image](https://github.com/user-attachments/assets/2b81ec80-05fe-4cce-bb9e-ee6befab5cb6)

**Comment by Bartupso** [comment]
I'm sorry for responding so late.  We tested Open AI and Claude well in GCA, but the other models are unfortunately slow. We continue to make improvements in GCA. After 1 month I expect it will run smoothly
