### ISSUE TITLE
some depdency is missing and cannot install per README.md

### ISSUE THREAD

**Issue by double12gzh** [Upsonic/Upsonic#23]
# Errors with installtion:

> C:\Users\jeffrey>pip3 install gpt-computer-assistant                                                                        WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.                          Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.                               To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.                                  Defaulting to user installation because normal site-packages is not writeable                                               Collecting gpt-computer-assistant                                                                                             Downloading gpt_computer_assistant-0.6.12.tar.gz (163 kB)                                                                      |████████████████████████████████| 163 kB 163 kB/s                                                                     ERROR: Could not find a version that satisfies the requirement langgraph==0.0.55 (from gpt-computer-assistant) (from ver    sions: 0.0.8)                                                                                                               ERROR: No matching distribution found for langgraph==0.0.55 (from gpt-computer-assistant)     

after install `langgraph` with command `pip3 install langgraph==0.0.55`, a new error occurred as follows:

> C:\Users\jeffrey>pip3 install gpt-computer-assistant                                                                
> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.                          Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.                               To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.                                  Defaulting to user installation because normal site-packages is not writeable                                               WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'Prox    yError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gpt-computer-assistant/                                   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'Prox    yError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gpt-computer-assistant/                                   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'Prox    yError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gpt-computer-assistant/                                   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'Prox    yError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gpt-computer-assistant/                                   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'Prox    yError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/gpt-computer-assistant/                                   ERROR: Could not find a version that satisfies the requirement gpt-computer-assistant==0.6.12 (from versions: none)         ERROR: No matching distribution found for gpt-computer-assistant==0.6.12 

                                                                                                                                                                               

run command `pip3 install gpt-computer-assistant==0.6.12` to install but still with above error.

# Enviroment:

> system: Win10
> 
> C:\Users\jeffrey>pip --version
> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of
> Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
> pip 24.0 from C:\Users\jeffrey\AppData\Roaming\Python\Python38\site-packages\pip (python 3.8)

**Comment by onuratakan** [comment]
Hmm, it seems about your python version, can you upgrade you python version to 3.12?

**Comment by onuratakan** [comment]
Hi, again, i just made a update and we just currently support >= 3.9

**Comment by double12gzh** [comment]
Great! It works well after upgrading my python version.
