### ISSUE TITLE
Adding custom llm generation ability

### ISSUE THREAD

**Issue by comeback01** [Upsonic/Upsonic#24]
I wanted to suggest you the possibility to customize the endpoint.

This allows the use of services compatible with OpenAI such as:

https://openrouter.ai
https://fireworks.ai
https://www.together.ai

The advantage of OpenRouter is that they also offer free endpoints.

Thank you for the help.

**Comment by Zhwt** [comment]
If base url is configurable, I think local LLMs(Ollama, etc...) will be supported automatically through [BerriAI/litellm](https://github.com/BerriAI/litellm) proxy.

**Comment by onuratakan** [comment]
Oh yeah, we can but what about vision capabilities, the services that you suggested have vision mode. Should we separate the vision mechanism.

**Comment by onuratakan** [comment]
I will add a support to set custom langchain llm class. With this we can be integrated many models above langchain.
