### ISSUE TITLE
Adding support to groq

### ISSUE THREAD

**Issue by onuratakan** [Upsonic/Upsonic#29]
Hello ! It would be cool to use groq api so that it will run a lot faster than openai or ollama (and it's free).

_Originally posted by @guepardlover77 in https://github.com/onuratakan/gpt-computer-assistant/issues/19#issuecomment-2146717808_

**Comment by Mideky-hub** [comment]
Hey! That would be awesome, I'll put a PR soon for this!

**Comment by Mideky-hub** [comment]
Can we assign me to this one?

**Comment by onuratakan** [comment]
Hey yeah, why not. Please.

**Comment by onuratakan** [comment]
We are fully open to contributions. Its our agents your and mine.

**Comment by Mideky-hub** [comment]
Perfect!
