### ISSUE TITLE
Can't find model.

### ISSUE THREAD

**Issue by SchooiCodes** [Upsonic/Upsonic#32]
I have created an API key via openai's website but the console outputs an error:
```openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}```

I cant understand if my api key is gpt3.5 or gpt4.

**Comment by onuratakan** [comment]
Ouu its so interesting? It seems gpt-4o not working on your api. Are you using an proxy?

**Comment by SchooiCodes** [comment]
No, I never installed a proxy myself. I am from Greece, which is where I live too and maybe gpt4o API keys are not supported(?) (By the way, hello neighbor!)

**Comment by zeak6464** [comment]
got the same error , and checked 
![image](https://github.com/onuratakan/gpt-computer-assistant/assets/2738141/189f970d-ec75-4baf-9a18-7066a839598d)
no gpt-4o at all listed

**Comment by onuratakan** [comment]
Hi, and <3 neighbor. Yeah i think its caused by location. But today we will add new llm sources include local models. So just wait a little bit.

**Comment by SchooiCodes** [comment]
Okay! Thanks for the help. Have a nice day!

**Comment by barnoloji** [comment]
Hocam selamlar aynı sorun ile karşılaştım. 

NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by onuratakan** [comment]
Selamlar, now we have gpt-4-turbo and gpt-3.5-turbo support.

As they capacity we cant make vision operations but still there is many feature.

**Comment by SchooiCodes** [comment]
Okay! Nice, thanks for the help.
