### ISSUE TITLE
 ole32 Windows

### ISSUE THREAD

**Issue by Andrecks** [Upsonic/Upsonic#34]
when launching computerassistant the error occurs and I have no idea why, I have ole32.dll in my C:\Windows\System32 folder. 
OSError: ctypes.util.find_library() did not manage to locate a library called 'ole32'

**Comment by Mideky-hub** [comment]
@Andrecks | Did you tried to do :
- Win + R
- cmd then Ctrl+Maj+Enter
- Enter again
- type "sfc /scannow" to scan your system for missing or corrupted packages

Tell me if this worked for you.

**Comment by dirkarnez** [comment]
@Andrecks did you have the solution? I just have same error but mine is just because my `%PATH%` is empty.

**Comment by Bartupso** [comment]
Sorry for the late reply. We will have a new version soon
