### ISSUE TITLE
Add Qwen-VL model?

### ISSUE THREAD

**Issue by brayevalerien** [Upsonic/Upsonic#35]
Qwen-VL ([ArXiv](https://arxiv.org/abs/2308.12966), [GitHub](https://github.com/QwenLM/Qwen-VL), [HugingFace](https://huggingface.co/Qwen/Qwen-VL)) shows very promising results on various tasks, would it be possible to add it to the project or at least consider it?

I have not read the full source code, but from what I've seen it should be pretty straight forward, I could probably do it when I've a bit of time.

**Comment by onuratakan** [comment]
Hi, thank you so much. I will make researches about it. Maybe gpt-computer-assistant will research =)
