### ISSUE TITLE
How can i run it?

### ISSUE THREAD

**Issue by MaelMatos** [Upsonic/Upsonic#40]
just installed the app,how i start it?
theres no launcher,i cant start it on cmd or python terminal

**Comment by onuratakan** [comment]
Hi, please just run it into your terminal:

```console
computerassistant
```

**Comment by willowforge** [comment]
> Hi, please just run it into your terminal:
> 
> ```
> computerassistant
> ```

I used pip install and my cdprompt is telling me the 'computerasssistant' command does not exist. Do I need to add anything to PATH?

**Comment by dannylank** [comment]
![image](https://github.com/onuratakan/gpt-computer-assistant/assets/37990621/982e1ce3-f963-4b8f-9d43-3fa6aee20a82)

**Comment by onuratakan** [comment]
Hi can you try this python script. Your error caused by your python installation actually (Adding Path).

@joshcheic @MaelMatos @dannylank 

```python
from gpt_computer_assistant import start

start()
```
