### ISSUE TITLE
Suggestions for new UI design.

### ISSUE THREAD

**Issue by SrijanSriv211** [Upsonic/Upsonic#44]
Using `PyQT webkit` or something like that to render the UI using Chromium engine and styling it using Html/CSS seems a pretty good idea to me. It allows for a better UI design and UX.

Also, personally I think the UI is very mobile-like. I mean it doesn't look like a desktop application. It would be cool if you expanded the screen size by a lot and then utilizing all the empty spaces properly with an intuitive design.

Also I just discovered this repo and I'm going to look into it, so maybe I'll create a PR for the same. Cool project though.

Also I think calling this project something like GPA (GPT Assistant) is kinda cool since GPA matches with GTA and GPT both. But yeah anyways cool project, appreciate the work.

**Comment by septatrix** [comment]
QT Webkit is pretty heavy on resources compared to just QT. It is also possible to style QT with stylesheets. Furthermore would this prevent closer and cooler integration in the future. For example, frameless windows with non-rectangular shapes. A long time ago (before GPT et al took off) I made such an app with clippy just for fun. Using QT Webkit would make this hard or impossible to my knowledge

**Comment by SrijanSriv211** [comment]
It's a good point. Actually just today I came across a new library [DearPyGUI](https://github.com/hoffstadt/DearPyGui) which is similar to [Dear ImGui](https://github.com/ocornut/imgui) but for python. Perhaps one could use it. I haven't explored that module properly yet since I discovered it today so I don't really know if it is a good candidate for better UI in this project or not but yeah I do agree with the point you made.

But I still think the UI is very mobile-like. Either making the UI like a proper desktop application or like how Siri comes up at top right corner of the screen in MacOS seems a better UI design to me. What are your opinions on it?

**Comment by septatrix** [comment]
> ...I don't really know if it is a good candidate for better UI in this project...

I am not sure I understand why you want to replace the toolkit? QT is very mature and capable.

> But I still think the UI is very mobile-like. Either making the UI like a proper desktop application or like how Siri comes up at top right corner of the screen in MacOS seems a better UI design to me. What are your opinions on it?

Apart from the big round buttons I would not say that the UI is mobile-like. Maybe it would be best if you provide a few sketches how you would image the UI to look like or what you want to be improved such that the maintainer has a better idea what you want.

I would actually go the opposite direction and say it should become less desktopy - or at least look less like it is from Windows XP, i.e. less blocky, less gray. Make the window frameless, make it look more organic (less rectangular), add icons to the buttons, introduce some colors and indicators (e.g. a red dot in the middle while recording).

**Comment by SrijanSriv211** [comment]
> I am not sure I understand why you want to replace the toolkit? QT is very mature and capable.

No actually I was just telling that today I discovered a new UI module in Python. It felt interesting to me and it has very intuitive design just like Dear ImGui for C++ so MAYBE it could POTENTIALLY be used for better UI and controls.

I don't really want to replace the toolkit. QT is obviously a great UI library. Hope it clears the confusion.



> Apart from the big round buttons I would not say that the UI is mobile-like

Maybe I wasn't able to describe what I meant by "mobile-like UI". Now as you've already pointed out the big round buttons (specially in the demo video they are unlabeled in the main application) doesn't look good and very easy to use. Apart from that I think it would be better to change the text-label box also if the essence current UI is to be preserved.

As I've already said in my previous reply, I think the way Siri pops up at the top right corner of the screen is pretty cool and the UI should quite similar to that style, cuz I think even if the window borders and it's plain background is just wasted screen space although the height and width of the application window is very small but still.

And maybe when we'll click that GPT Assistant icon hovering on the top right corner then it will open up a lot more options for us to play with and we can obviously by closing options windows move the UI back to just that floating icon but the application would still be usable in the options window as well.



> I would actually go the opposite direction and say it should become less desktopy - or at least look less like it is from Windows XP, i.e. less blocky, less gray. Make the window frameless, make it look more organic (less rectangular), add icons to the buttons, introduce some colors and indicators (e.g. a red dot in the middle while recording).

What you have said can be applied to that options window thing I was just talking about. It's a pretty cool concept. The direction you chose is definitely a cool, modern and fresh UI design.


I mean at the end of the day, our goal should not only be to make the core application functionable and great but also the UI to be very intuitive and easy to use. What I'm saying is that anyone who will use this app should only take a couple of minutes to wrap their head around the UI and controls and the core application functions and UI must be so well designed that they the users should feel like its so natural to use.

**Comment by onuratakan** [comment]
Thanks for this amazing conversation. For now we will continue with qt5 but we will improve ux for feeling better.

**Comment by onuratakan** [comment]
But lets convert here to an general discuss section about GUI.

- [x]  Collapse
- [x] New Logo
- [x] Typing Animation
- [ ] ...

**Comment by SrijanSriv211** [comment]
> Thanks for this amazing conversation. For now we will continue with qt5 but we will improve ux for feeling better.

That cool! Thank you as well for starting this project.

**Comment by onuratakan** [comment]
https://github.com/onuratakan/gpt-computer-assistant/assets/41792982/b0e82a3d-d262-472b-80bb-e7e23ee902ef

Can i get your feedbacks? @septatrix @SrijanSriv211

**Comment by Mideky-hub** [comment]
Personally, I like it a lot!

**Comment by SrijanSriv211** [comment]
> Recording.2024-06-09.165045.mp4 
> Can i get your feedbacks? @septatrix @SrijanSriv211

Yeah, now it's looking much better. Specially with that dark mode, and additional settings buttons. Great improvement!

**Comment by onuratakan** [comment]
Surprise!

![image](https://github.com/onuratakan/gpt-computer-assistant/assets/41792982/98bf1dde-9ed0-417e-b460-4105b43231ed)

**Comment by SrijanSriv211** [comment]
> Surprise!
> 
> ![image](https://private-user-images.githubusercontent.com/41792982/338939631-98bf1dde-9ed0-417e-b460-4105b43231ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTk5NzEsIm5iZiI6MTcxODE5OTY3MSwicGF0aCI6Ii80MTc5Mjk4Mi8zMzg5Mzk2MzEtOThiZjFkZGUtOWVkMC00MTdlLWI0NjAtNDEwNWI0MzIzMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzNDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZjEyOWRiNWZiZjIyZjQzNzNmZTQ1MDczNDBjZGVmMTcyYTBhZWZiYmMyOGY1N2E5OGM1Y2M4NDAxMDI3YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8iJPqBomG2ooNlGllniN5XkhMOmwOazPKlokoX5kXM0)

Dude! That's even better!! However those up-down arrow scroll buttons are looking annoying to me personally. It would be great if it could be removed or styled. Also the radius of the app window is a little too much. I'll suggest to half it from the current radius. Still great progress though!

**Comment by onuratakan** [comment]
> > Surprise!
> > ![image](https://private-user-images.githubusercontent.com/41792982/338939631-98bf1dde-9ed0-417e-b460-4105b43231ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTk5NzEsIm5iZiI6MTcxODE5OTY3MSwicGF0aCI6Ii80MTc5Mjk4Mi8zMzg5Mzk2MzEtOThiZjFkZGUtOWVkMC00MTdlLWI0NjAtNDEwNWI0MzIzMWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzNDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZjEyOWRiNWZiZjIyZjQzNzNmZTQ1MDczNDBjZGVmMTcyYTBhZWZiYmMyOGY1N2E5OGM1Y2M4NDAxMDI3YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8iJPqBomG2ooNlGllniN5XkhMOmwOazPKlokoX5kXM0)
> 
> Dude! That's even better!! However those up-down arrow scroll buttons are looking annoying to me personally. It would be great if it could be removed or styled. Also the radius of the app window is a little too much. I'll suggest to half it from the current radius. Still great progress though!

Realy good feedbacks and got it. For now i am just working for native distributions. After that i will.

**Comment by onuratakan** [comment]
a minimal update for top bar:

https://github.com/onuratakan/gpt-computer-assistant/assets/41792982/8ec4faeb-0fc3-4d86-b1c8-fcb4281fab69

**Comment by Macaulay1234** [comment]
> Using `PyQT webkit` or something like that to render the UI using Chromium engine and styling it using Html/CSS seems a pretty good idea to me. It allows for a better UI design and UX.
> 
> Also, personally I think the UI is very mobile-like. I mean it doesn't look like a desktop application. It would be cool if you expanded the screen size by a lot and then utilizing all the empty spaces properly with an intuitive design.
> 
> Also I just discovered this repo and I'm going to look into it, so maybe I'll create a PR for the same. Cool project though.
> 
> Also I think calling this project something like GPA (GPT Assistant) is kinda cool since GPA matches with GTA and GPT both. But yeah anyways cool project, appreciate the work.

**Comment by DawoodTouseef** [comment]
Using React Js and Fast APi and PyQt5 we can build a new UI for Computer assistant 
```
url:https://www.pythonguis.com/examples/python-web-browser/
```
The above given link is the Url how we can build a Browser using the above example we can build a UI using react js and FastAPI

**Comment by SrijanSriv211** [comment]
> Using React Js and Fast APi and PyQt5 we can build a new UI for Computer assistant
> 
> ```
> url:https://www.pythonguis.com/examples/python-web-browser/
> ```
> 
> The above given link is the Url how we can build a Browser using the above example we can build a UI using react js and FastAPI

I think as of now sticking to just PyQT with no browser related stuff involved a better option. It could be taken into consideration when the project grows a lot more. And completely ready for non-programmer people to use it, At least as of now just using the vanilla PyQT features are pretty good i guess.
