### ISSUE TITLE
Why just Ubuntu?

### ISSUE THREAD

**Issue by ThatOneCalculator** [Upsonic/Upsonic#48]
This seems to work fine on any Linux distro that can run Python 3.9 (tested on Arch), so I'm not sure why the documentation is "Windows, macOS, and Ubuntu" instead of "Windows, macOS, and Linux"

**Comment by onuratakan** [comment]
Actualy, you are so right. I just think about native app support. But linux users just like me and you can easily install it via terminal.

**Comment by ThatOneCalculator** [comment]
Yeah, I just think that saying it's "for Ubuntu" instead of "for Linux" might discourage other Linux users from using it.
