### ISSUE TITLE
how to use ollama?

### ISSUE THREAD

**Issue by Nesbesss** [Upsonic/Upsonic#55]

**Comment by onuratakan** [comment]
Hi, just go to llm settings and select an ollama model.

![image](https://github.com/onuratakan/gpt-computer-assistant/assets/41792982/92969698-9a6d-45f0-a4e5-ef38d726a607)

**Comment by nessystudio** [comment]
Can't we choose the models we have installed too? I want to use a tuned version of Llava with lama3, or Nvidia Nemo which just got a multimodal update.

**Comment by onuratakan** [comment]
> Can't we choose the models we have installed too? I want to use a tuned version of Llava with lama3, or Nvidia Nemo which just got a multimodal update.

Ouu its a good point actually i will generate a new issue for this.

https://github.com/onuratakan/gpt-computer-assistant/issues/101
