### ISSUE TITLE
Bug: object has no attribute 'should_paint'

### ISSUE THREAD

**Issue by Wandalen** [Upsonic/Upsonic#60]
Hello! I have issue with

```
  File "C:\Users\kosli\AppData\Roaming\Python\Python312\site-packages\gpt_computer_assistant\gpt_computer_assistant.py", line 226, in paintEvent
    if not self.should_paint:
           ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'should_paint'
```

How to fix that? Do I miss something?

**Comment by onuratakan** [comment]
Hi can you upgrade?

`pip3 install gpt-computer-assistant --upgrade`

**Comment by onuratakan** [comment]
@Wandalen Is it fixed?

**Comment by Wandalen** [comment]
![image](https://github.com/onuratakan/gpt-computer-assistant/assets/7414255/2e560f52-66d6-40e0-a5ba-e2f699fab6bb)
Tried to do that, but that didn't help.

**Comment by Wandalen** [comment]
Tried to do that, but that didn't help.

![image](https://github.com/onuratakan/gpt-computer-assistant/assets/7414255/ec3d2454-2916-47ed-984c-7b4ec4fc7dfb)

**Comment by onuratakan** [comment]
Actualy pip doesnt upgrade in the first time of run. Please run again the update command. or


```console
pip3 install gpt-computer-assistant==0.8.9
```

**Comment by BenjaminMichaelis** [comment]
I am getting this error as well

**Comment by vietnguyengit** [comment]
Eventually, everyone starting this project from scratch will encounter this issue. Dependencies defined in `requirements.txt` left unpinned can lead to conflicts, especially with dependencies of dependencies. Project owners should consider implementing a better dependency management tool such as `poetry`, check out the following sample: https://github.com/openai/openai-python/blob/main/pyproject.toml

**Comment by Mideky-hub** [comment]
@onuratakan that was fixed in my patch
