### ISSUE TITLE
Making wide input box and wrapping

### ISSUE THREAD

**Issue by mdwoicke** [Upsonic/Upsonic#63]
Awesome project! Is it possible to have a bigger display that can wrap lines instead of a single line? Would be so beneficial when reading responses that have a lot of text.  

Thanks! Keep up the awesome work!

**Comment by onuratakan** [comment]
Hi yes its so true. i will add.

**Comment by mdwoicke** [comment]
Awesome, thanks! 👍

**Comment by onuratakan** [comment]
https://github.com/onuratakan/gpt-computer-assistant/assets/41792982/c609a010-064d-41ee-ad57-910b424235af
