### ISSUE TITLE
Adding Azure Open AI 

### ISSUE THREAD

**Issue by Abhishekxdg** [Upsonic/Upsonic#74]
Please add azure open ai to this

**Comment by Mideky-hub** [comment]
Sure, working on it

**Comment by yidasanqian** [comment]
> Sure, working on it

@Mideky-hub @onuratakan How long is left to support?

**Comment by adminsde** [comment]
Hi. ss now azure openai available on the gpt assistant?

**Comment by Bartupso** [comment]
Sorry for the late reply. Yes, support to azure open AI. We will have a new version soon.
