### ISSUE TITLE
Adding Gemini 1.5-Pro/Flash

### ISSUE THREAD

**Issue by datrip** [Upsonic/Upsonic#84]
Hi, any plans to add Google's LLMs? Both are multimodal and have a very useful free tier for the API, so a lot of people use it.

**Comment by Mideky-hub** [comment]
Yes sure, just wrote a universal backend dictionary for adding AI models to the assistant. It will be made shortly!

**Comment by Merlinvt** [comment]
I think providing the ability to specify your own model with a base URL would open up many possibilities. You could use OpenRouter or a similar service and access models like Gemini, Claude, or any other model you want for the same price.

Sure, having a lightllm implementation would make this possible too. But in the meantime, allowing users to add a custom model string when selecting a custom base URL would enable most of these capabilities. You might want to include a warning that the model needs to support vision or other specific features.

**Comment by Mideky-hub** [comment]
Sure, I'll work on it, but in the meantime we'll have a parallel implementation of an hardcoded model implementation, in less than a week a custom selection model will be able to be done by the user

**Comment by Mideky-hub** [comment]
See #111
