### ISSUE TITLE
Can this work with the Assistant API?

### ISSUE THREAD

**Issue by GrushBrush** [Upsonic/Upsonic#9]

**Comment by onuratakan** [comment]
Hi actualy its logical and i want to add. I will add to roadmap and looking for.

**Comment by codermaker2022** [comment]
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Inpackages\openai\_base_client.py", line 1020, in _requestcorrect API key provided: CHANGE_ME. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_errcorrect API key provided: CHANGE_ME. You can find your API key at https://platform.openai.or', 'param': None, 'code': 'invalid_api_key'}}                        , 'param': None, 'code': 'invalid_api_key'}}
