### ISSUE TITLE
UI Improvement 

### ISSUE THREAD

**Issue by mdwoicke** [Upsonic/Upsonic#93]
I noticed one of the latest builds shows improvement to input box. Is this pertaining to making it mult-line for readability on bigger responses? I upgraded but did not see any changes to the input box overall.

**Comment by onuratakan** [comment]
Hi actualy we made a big update but we just got some errors about deployment pipeline. But now fixed. So just try:


```console
pip3 install gpt-computer-assistant==0.9.2
```

**Comment by mdwoicke** [comment]
Awesome, thanks!!!
