### ISSUE TITLE
Adding Documentation and Improving Code Quality.

### ISSUE THREAD

**Issue by KramStyles** [Upsonic/Upsonic#95]
### Description
Hello and good day. I would love to propose adding comprehensive code documentation, which impacts readability and maintainability to the codebase. I propose enhancing it by adding comments, docstrings, and Sphinx documentation.

### Goals
1. Improve code readability for contributors.
2. Facilitate understanding of complex logic.
3. Enable automatic documentation generation.

### Areas to Address
- [x] #99
- [x] #100
- [ ] Set up Sphinx for API documentation.
- [ ] Provide initial PRs for adding comments and docstrings to key modules.

If this is considered, I'd love to be a part of the contribution, study the code, add comments, docstrings (numpy) and sphinx documentation. If possible and approved, PEP8 code style can be employed.

Please let me know if this proposal aligns with the project's goals, and if there are any specific guidelines or preferences to follow while implementing these changes.

**Comment by onuratakan** [comment]
Firstly, thank you too much, secondly we have another plan for documentation but the other things totally accepted and needed.

**Comment by onuratakan** [comment]
I will create sub-issues for these include documentation website process.

**Comment by onuratakan** [comment]
I will add comments, can you write docstrings @KramStyles ?

**Comment by KramStyles** [comment]
Sure. I'm on it
